from pathlib import Path

import joblib
import numpy as np


BASE_DIR = Path(__file__).resolve().parent

MODEL_PATH = (
    BASE_DIR
    / "models"
    / "nutrition_model.joblib"
)


def load_model():

    if not MODEL_PATH.exists():

        raise FileNotFoundError(
            f"Model not found: {MODEL_PATH}. "
            f"Run train_models.py first."
        )

    return joblib.load(
        MODEL_PATH
    )


def predict_nutrition(
    moisture,
    ph,
    temperature,
    humidity,
    nir_values
):

    model_package = load_model()

    model = model_package["model"]

    expected_nir_values = len(
        model_package["nir_wavelengths"]
    )

    nir_values = list(
        nir_values
    )

    if len(nir_values) != expected_nir_values:

        raise ValueError(
            f"Expected "
            f"{expected_nir_values} NIR values, "
            f"but received "
            f"{len(nir_values)}."
        )

    features = np.array(
        [[
            float(moisture),
            float(ph),
            float(temperature),
            float(humidity),
            *[
                float(value)
                for value in nir_values
            ]
        ]],
        dtype=float
    )

    prediction = model.predict(
        features
    )[0]

    return {

        "protein":
            round(
                float(prediction[0]),
                2
            ),

        "fiber":
            round(
                float(prediction[1]),
                2
            ),

        "energy":
            round(
                float(prediction[2]),
                2
            ),

        "model":
            "RandomForestRegressor",

        "mode":
            "synthetic_demo",

        "validated":
            False,

        "warning":
            "Prediction generated by a "
            "synthetic demo model and is "
            "not laboratory validated."
    }


if __name__ == "__main__":

    demo_nir = [
        0.02
        for _ in range(41)
    ]

    result = predict_nutrition(
        moisture=14.0,
        ph=5.8,
        temperature=28.0,
        humidity=65.0,
        nir_values=demo_nir
    )

    print(result)
